### ISSUE TITLE
Get familiar with storybook

### ISSUE THREAD

**Issue by codeKenta** [kenone/kringlan#1]
Find out what storybook is.

After installing the app dependencies, start storybook with `yarn storybook` to find the representation of the UI-components.

Resources
https://storybook.js.org/tutorials/intro-to-storybook/

or find something else on internet

**Comment by mrautenberg** [comment]
@tompahans assigned the ticket to you, please assign me as reviewer on the PR.

**Comment by mrautenberg** [comment]
@tompahans please create a new block in`src/api/__mock__/cms/blocks` for storybook which takes in the following props:

- Heading
- Text
- Image
- Button with label
