### ISSUE TITLE
TIME FOR SANITY

### ISSUE THREAD

**Issue by codeKenta** [kenone/kringlan#15]
When we reach this ticket, it's time to look at sanity and soon complete all current blocks with cms-support.

First watch this 20 minutes crash course

https://www.youtube.com/watch?v=32RP-sG1njE

**Comment by tompahans** [comment]
Serenity now inSANITY later

**Comment by codeKenta** [comment]
Are you cheating the priority in the backlog? It's suggestable to move through the list from top to the bottom :)
