### ISSUE TITLE
Content block

### ISSUE THREAD

**Issue by mrautenberg** [kenone/kringlan#34]
see figma file:

https://www.figma.com/file/e70ywBtOSjIdy0O1QxnsPR/Kringlan?node-id=0%3A1

The design should work for different screen sizes, if you have any questions ping @kenone for design feedback.

assign me as PR for a preview of storybook version (the scope of this ticket) and remember to https://github.com/kenone/kringlan/issues/28

**Comment by tompahans** [comment]
We already have a working content block
